

labels = [
    ('Apple', False, 'Apple scab'),
    ('Apple', False, 'Black rot'),
    ('Apple', False, 'Cedar apple rust'),
    ('Apple', True, 'healthy'),
    ('Blueberry', True, 'healthy'),
    ('Cherry including sour', True, 'healthy'),
    ('Cherry including sour', False, 'Powdery mildew'),
    ('Corn maize', False, 'Cercospora leaf spot'),
    ('Corn maize', False, 'Common rust '),
    ('Corn maize', True, 'healthy'),
    ('Corn maize', False, 'Northern Leaf Blight'),
    ('Grape', False, 'Black rot'),
    ('Grape', False, 'Esca Black Measles'),
    ('Grape', True, 'healthy'),
    ('Grape', False, 'Leaf blight Isariopsis Leaf Spot'),
    ('Orange', False, 'Haunglongbing Citrus greening'),
    ('Peach', False, 'Bacterial spot'),
    ('Peach', True, 'healthy'),
    ('Pepper, bell', False, 'Bacterial spot'),
    ('Pepper, bell', True, 'healthy'),
    ('Potato', False, 'Early blight'),
    ('Potato', True, 'healthy'),
    ('Potato', False, 'Late blight'),
    ('Raspberry', True, 'healthy'),
    ('Soybean', True, 'healthy'),
    ('Squash', False, 'Powdery mildew'),
    ('Strawberry', True, 'healthy'),
    ('Strawberry', False, 'Leaf scorch'),
    ('Tomato', False, 'Bacterial spot'),
    ('Tomato', False, 'Early blight'),
    ('Tomato', True, 'healthy'),
    ('Tomato', False, 'Late blight'),
    ('Tomato', False, 'Leaf Mold'),
    ('Tomato', False, 'Septoria leaf spot'),
    ('Tomato', False, 'Spider mites'),
    ('Tomato', False, 'Target Spot'),
    ('Tomato', False, 'Tomato mosaic virus'),
    ('Tomato', False, 'Tomato Yellow Leaf Curl Virus')
]
